# Generated by Django 5.1.5 on 2025-02-14 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('Id', models.IntegerField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=40, unique=True)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('Id', models.IntegerField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=40, unique=True)),
                ('Password', models.CharField(max_length=10)),
                ('Branch', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectDetails',
            fields=[
                ('Id', models.IntegerField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=40, unique=True)),
                ('No_of_topics', models.IntegerField()),
                ('TeacherId', models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacherdetails'))),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('Id', models.IntegerField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=40, unique=True)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
    ]
