# Generated by Django 5.1.5 on 2025-04-06 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(default='it', on_delete=django.db.models.deletion.CASCADE, to='api.branch'),
        ),
    ]
