# Generated by Django 5.1.5 on 2025-03-29 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_quiz_date_created_quiz_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquiz',
            name='attempt_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentquiz',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentquiz',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
