# Generated by Django 5.1.5 on 2026-02-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_quiz_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
